### ISSUE TITLE
[Bug] Duplicated UI

### ISSUE THREAD

**Issue by rmasoni** [Norc/foundry-custom-hotbar#70] opened 2020-08-23 09:22 UTC
**OS:** macOS Electrum app and Google Chrome. Doesn't happen on Firefox.

It looks like the UI is somehow duplicated. The duplicate isn't interactive though.

Also, the macro button inner shadow is too strong compared to the original hotbar.

![custom-hotbar-duplicate-ui](https://user-images.githubusercontent.com/62244/90975221-c244a880-e508-11ea-9120-8f965e7da693.gif)

**Comment by InflamedSebi** [comment] 2020-09-14 20:01
Same for node.js dedicated install + chrome.
Does not happen in Firefox, but switching from chrome is no option, other extensions rely on chrome.

**Comment by LadySaga** [comment] 2020-10-11 21:35
I just wrote on the modules-troubleshooting discord, and then noticed that both issues i reported were here. So yeah, I can confirm this as well.
dnd5e 0.96 and fvtt 0.6.6 right now, but i had the same issue before as well.
I get this error in firefox, in chrome and in the native application.

**Comment by rmasoni** [comment] 2020-10-11 22:43
I went back and forth with Norc on this. Doesn't seem to be an issue anymore on Foundry 0.7.x.

**Comment by Norc** [comment] 2020-10-21 17:55
Closing because 0.7.x will hit stable *very* soon at this point, will reopen if it is reproduced in 0.7.5+

**Closed by Norc** 2020-10-21 17:55 UTC

**Comment by Norc** [comment] 2020-10-21 18:50
Just as an update, I did see this in an old version of Firefox once, but updating solved it for me. Hopefully this is really dead.

**Comment by LadySaga** [comment] 2020-10-22 00:37
Oh, great news and looking forward. I will probably wait a bit with fully upgrading, so more modules catch up, but I'm considering running a parallell double install for 0.6.6 and 0.7.5 so i can migrate stuff over when things start running more smoothly, so... if i can getthat running i might even find out today, or tomorrow! :)
